# Generated by Django 6.0.2 on 2026-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='tier',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
