# Generated by Django 6.0.2 on 2026-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendations_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
