# Generated by Django 6.0.2 on 2026-04-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_communitysong_delete_communitymodel'),
        ('recommendations', '0003_recommendations_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='books.book'),
        ),
    ]
