# Generated by Django 6.0.2 on 2026-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
