# Generated by Django 6.0.2 on 2026-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_comment_count_reviewcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
