# Generated by Django 6.0.2 on 2026-02-22 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("authors", models.JSONField(default=list)),
                (
                    "isbn_10",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "isbn_13",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("cover_url", models.URLField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("publish_date", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("genres", models.JSONField(default=list)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
