# Generated by Django 6.0.2 on 2026-04-11 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_google_books_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookShelfTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("mention_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_tags",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artist_name", models.CharField(max_length=255)),
                ("song_title", models.CharField(blank=True, max_length=255, null=True)),
                ("mention_count", models.BooleanField(default=0)),
                ("raw_mention", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_songs",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
