# Generated by Django 6.0.2 on 2026-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookshelftag_communitymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="goodreads_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="goodreads_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="scraped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
