# Generated by Django 6.0.2 on 2026-04-11 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_goodreads_id_book_goodreads_url_book_scraped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('spotify_verified', models.BooleanField(default=False)),
                ('raw_mention', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_songs', to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='CommunityModel',
        ),
    ]
