const CLIENT_ID = import.meta.env.VITE_SPOTIFY_CLIENT_ID;
const REDIRECT_URI = import.meta.env.VITE_SPOTIFY_REDIRECT_URI || `${window.location.origin}/spotify-callback`;
const SCOPES = "playlist-modify-private playlist-modify-public";
const SPOTIFY_API = "https://api.spotify.com";

// ── PKCE helpers ──────────────────────────────────────────────────────────────

function generateRandomString(length) {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  const values = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(values).map((v) => chars[v % chars.length]).join("");
}

async function sha256(plain) {
  const encoder = new TextEncoder();
  const data = encoder.encode(plain);
  return crypto.subtle.digest("SHA-256", data);
}

function base64URLEncode(buffer) {
  return btoa(String.fromCharCode(...new Uint8Array(buffer)))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

// ── Auth ──────────────────────────────────────────────────────────────────────

export async function initiateSpotifyAuth(bookId) {
  const verifier = generateRandomString(128);

  sessionStorage.setItem("spotify_code_verifier", verifier);
  sessionStorage.setItem("spotify_book_id", bookId);

  const challenge = base64URLEncode(await sha256(verifier));

  const params = new URLSearchParams({
    client_id: CLIENT_ID,
    response_type: "code",
    redirect_uri: REDIRECT_URI,
    code_challenge_method: "S256",
    code_challenge: challenge,
    scope: SCOPES,
    state: bookId,
    show_dialog: true,
  });

  window.location.href = `https://accounts.spotify.com/authorize?${params}`;
}

// Cache in-flight token exchanges by code so StrictMode's double-invoke
// shares one HTTP request instead of sending the code twice (codes are single-use).
const tokenCache = new Map();

export function exchangeCodeForToken(code) {
  if (tokenCache.has(code)) {
    return tokenCache.get(code);
  }

  const promise = (async () => {
    const verifier = sessionStorage.getItem("spotify_code_verifier");

    const res = await fetch("https://accounts.spotify.com/api/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: CLIENT_ID,
        grant_type: "authorization_code",
        code,
        redirect_uri: REDIRECT_URI,
        code_verifier: verifier,
      }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.error_description || err.error || "Token exchange failed");
    }

    const data = await res.json();
    console.log("SCOPES:", data.scope);
    sessionStorage.removeItem("spotify_code_verifier");
    await new Promise(r => setTimeout(r, 1000));
    return data.access_token;
  })();

  tokenCache.set(code, promise);
  return promise;
}

// ── Spotify API wrapper ───────────────────────────────────────────────────────

async function spotifyFetch(path, token, method = "GET", body = null) {
  const res = await fetch(`${SPOTIFY_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    const msg = err?.error?.message || err?.error_description || JSON.stringify(err);
    throw new Error(msg || `Spotify API error ${res.status}`);
  }

  return res.status === 204 ? null : res.json();
}

// ── Track search ──────────────────────────────────────────────────────────────

async function searchTrack(token, song, artist) {
  const q = encodeURIComponent(`track:${song} artist:${artist}`);
  const data = await spotifyFetch(`/v1/search?q=${q}&type=track&limit=1`, token);
  return data?.tracks?.items?.[0]?.uri ?? null;
}

// ── Main entry point ──────────────────────────────────────────────────────────

export async function createSpotifyPlaylist(token, bookTitle, bookAuthor, songs, onProgress) {
  const me = await spotifyFetch("/v1/me", token);
  console.log("USER:", me.id);

  onProgress("Creating playlist…");
  const playlist = await spotifyFetch(
    `/v1/me/playlists`,
    token,
    "POST",
    {
      name: `${bookTitle} — Reading Soundtrack`,
      description: `Reading playlist for "${bookTitle}" by ${bookAuthor}. Generated by PageTurner.`,
      public: false,
    },
  );

  console.log("PLAYLIST OWNER:", playlist.owner.id);
  await new Promise(r => setTimeout(r, 1200));

  onProgress(`Searching for ${songs.length} tracks…`);
  const searchResults = await Promise.allSettled(
    songs.map(({ song, artist }) => searchTrack(token, song, artist)),
  );

  const uris = [];
  const notFound = [];
  searchResults.forEach((result, i) => {
    const { song, artist } = songs[i];
    const uri = result.status === "fulfilled" ? result.value : null;
    if (uri) {
      uris.push(uri);
    } else {
      notFound.push(`${song} — ${artist}`);
    }
  });

  if (uris.length > 0) {
    onProgress("Adding tracks to playlist…");
    for (let i = 0; i < uris.length; i += 100) {
      await spotifyFetch(`/v1/playlists/${playlist.id}/tracks`, token, "POST", {
        uris: uris.slice(i, i + 100),
      });
    }
  }

  return {
    playlistUrl: playlist.external_urls.spotify,
    tracksAdded: uris.length,
    tracksNotFound: notFound,
    total: songs.length,
  };
}
